In [5]:
#1.Create a null vector of size 10 but the fifth value which is 1.
import numpy as np
arr = np.zeros(10,dtype = int)
arr[4] = 1
print(arr)

[0 0 0 0 1 0 0 0 0 0]


In [6]:
#2.Create a vector with values ranging from 10 to 49.
import numpy as np
arr = np.arange(10,49)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
#3.Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
arr = np.arange(0,9).reshape(3,3)
print(arr)

In [7]:
#4.Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np
arr = np.nonzero([1,2,0,0,4,0])
print(arr)

(array([0, 1, 4]),)


In [8]:
#5.Create a 10x10 array with random values and find the minimum and maximum values.
arr = np.nonzero([1,2,0,0,4,0])
print(arr)
import numpy as np
arr = np.random.randint(100,size =(10,10))
print(arr)
print(np.min(arr))
print(np.max(arr))

(array([0, 1, 4]),)
[[ 5 54 45 88 49 80 60 82 53 24]
 [79 18 88 71 14 38 75 98 83 60]
 [39 99 92 70 31 78 33 94 17 59]
 [20 33 83  4  5 96  6 43 84 79]
 [13 69 11 95 38 16  8 90 57 91]
 [78 65 96 64  8 30 72 60 59 92]
 [45 13 71 92 31 36 79 70 92 70]
 [91 70 70 99 12  0 45 41  2 56]
 [37 47 58 17 38 59 81 67 42 21]
 [29 38 53 16  1 13  9 34 60 11]]
0
99


In [9]:
#Create a random vector of size 30 and find the mean value.
import numpy as np
arr = np.random.random(30)
print(arr)
print(np.mean(arr))

[0.41174289 0.63581436 0.76283433 0.67337108 0.10462706 0.75979732
 0.62638359 0.03921185 0.66276846 0.25308703 0.74605052 0.51415812
 0.69449885 0.32612994 0.63298196 0.1680371  0.12945685 0.3351373
 0.69809234 0.37621107 0.84480312 0.35798562 0.57997496 0.51394639
 0.02264389 0.1558978  0.40205599 0.93887633 0.82778299 0.69334997]
0.49625696849382606
